### ISSUE TITLE
Environtment?

### ISSUE THREAD

**Issue by bimadrd** [rcantini/speech_emotion_recognition#1]
Could you give some little note about the environments that you used to? such as what python version and each package version?
Thanks

**Comment by rcantini** [comment]
Hi, I've uploaded the requirements file and also listed the requirements in the "readme" section. I used Python version 3.7.5.
You can find further information about this application on my blog post [here](https://riccardo-cantini.netlify.app/post/speech_emotion_detection/).

[requirements.txt](https://github.com/rcantini/speech_emotion_recognition/files/5887018/requirements.txt)

**Comment by bimadrd** [comment]
> Hi, I've uploaded the requirements file and also listed the requirements in the "readme" section. I used Python version 3.7.5.
> You can find further information about this application on my blog post [here](https://riccardo-cantini.netlify.app/post/speech_emotion_detection/).
> 
> [requirements.txt](https://github.com/rcantini/speech_emotion_recognition/files/5887018/requirements.txt)

thank you so much
