### ISSUE TITLE
ModuleNotFoundError: No module named 'EmotionRecognition'

### ISSUE THREAD

**Issue by SherlockHusky** [rcantini/speech_emotion_recognition#3]
Could you please help me with this error?  I've downloaded all the same version packages that needed to run, but this error occurred, and 'EmotionRecognition' cannot be downloaded with pip....

**Comment by SherlockHusky** [comment]
By the way, the error is located in model.py

**Comment by rcantini** [comment]
You have not to download nothing, the module EmotionRecognition is the project itself.
In particular, in the line "import EmotionRecognition.preprocessing as pre_proc" I import the module preprocessing.py I have written and placed beside model.py in the folder EmotionRecognition.
So, just correct this import to correctly point to preprocessing.py: "import preprocessing as pre_proc" or something similar should work, based on the folder structure you have.
BTW, if you found this implementation interesting, please star the repo and read my blog post about that! :)
Cheers,
Riccardo.

**Comment by SherlockHusky** [comment]
Thank you ! It's solved and I'll star your repo
